"""
YOLO 微调脚本 — 针对 Task B 的 3 类 YCB 物体
用法:
    conda activate perception
    python train_yolo.py

训练数据格式 (YOLO 格式):
    taskb_perception/datasets/
    ├── images/
    │   ├── train/
    │   │   ├── frame_0001.png
    │   │   └── ...
    │   └── val/
    │       ├── frame_0100.png
    │       └── ...
    └── labels/
        ├── train/
        │   ├── frame_0001.txt   # class_id cx cy w h (归一化)
        │   └── ...
        └── val/
            ├── frame_0100.txt
            └── ...

class_id 映射:
    0: sugar_box
    1: mustard_bottle
    2: banana

训练策略:
    1. 先用 generate_synthetic_dataset.py 生成合成数据
    2. 再用本脚本微调 YOLOv11
    3. 导出 ONNX/TensorRT 用于推理加速
"""

import os
import sys
import argparse
from pathlib import Path

# 添加当前目录
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def create_dataset_yaml(output_path: str):
    """生成 YOLO 训练用的 dataset.yaml"""
    yaml_content = f"""# ATEC 2026 Task B — YCB Object Detection Dataset
# Auto-generated by train_yolo.py

path: {os.path.abspath('datasets')}
train: images/train
val: images/val

# Number of classes
nc: 3

# Class names
names:
  0: sugar_box
  1: mustard_bottle
  2: banana
"""
    with open(output_path, 'w') as f:
        f.write(yaml_content)
    print(f"[train_yolo] Created dataset config: {output_path}")


def check_dataset():
    """检查训练数据是否存在"""
    required_dirs = [
        'datasets/images/train',
        'datasets/images/val',
        'datasets/labels/train',
        'datasets/labels/val',
    ]
    for d in required_dirs:
        if not os.path.isdir(d):
            return False

    train_imgs = list(Path('datasets/images/train').glob('*.png')) + \
                 list(Path('datasets/images/train').glob('*.jpg'))
    if len(train_imgs) == 0:
        return False

    return True


def main():
    parser = argparse.ArgumentParser(description="Fine-tune YOLO for Task B objects")
    parser.add_argument('--model', type=str, default='yolo11n.pt',
                        help='Base model (yolo11n.pt, yolo11s.pt, yolo11m.pt)')
    parser.add_argument('--epochs', type=int, default=50,
                        help='Training epochs')
    parser.add_argument('--batch', type=int, default=16,
                        help='Batch size (reduce if OOM)')
    parser.add_argument('--imgsz', type=int, default=640,
                        help='Image size')
    parser.add_argument('--device', type=str, default='cuda:0',
                        help='Training device')
    parser.add_argument('--lr', type=float, default=0.001,
                        help='Initial learning rate')
    parser.add_argument('--export', action='store_true', default=True,
                        help='Export to ONNX after training')
    parser.add_argument('--resume', action='store_true', default=False,
                        help='Resume from last checkpoint')
    args = parser.parse_args()

    print("=" * 60)
    print("  ATEC 2026 Task B — YOLO Fine-tuning")
    print("=" * 60)

    # ---- 检查数据集 ----
    if not check_dataset():
        print("\n" + "!" * 60)
        print("  NO TRAINING DATA FOUND!")
        print("  Run generate_synthetic_dataset.py first:")
        print("    python generate_synthetic_dataset.py")
        print("!" * 60)
        sys.exit(1)

    print(f"\nDataset: {os.path.abspath('datasets')}")
    print(f"Base model: {args.model}")
    print(f"Epochs: {args.epochs}")
    print(f"Batch size: {args.batch}")
    print(f"Image size: {args.imgsz}")
    print(f"Device: {args.device}")

    # ---- 生成 dataset.yaml ----
    yaml_path = 'datasets/dataset.yaml'
    create_dataset_yaml(yaml_path)

    # ---- 训练 ----
    print("\n[1/2] Starting YOLO fine-tuning...\n")

    try:
        from ultralytics import YOLO

        # 加载预训练模型
        model = YOLO(args.model)

        # 训练
        results = model.train(
            data=yaml_path,
            epochs=args.epochs,
            batch=args.batch,
            imgsz=args.imgsz,
            device=args.device,
            lr0=args.lr,
            lrf=0.01,               # final lr factor
            momentum=0.937,
            weight_decay=0.0005,
            warmup_epochs=3,
            warmup_momentum=0.8,
            box=7.5,                 # box loss gain
            cls=0.5,                 # cls loss gain
            dfl=1.5,                 # dfl loss gain
            hsv_h=0.015,             # HSV-Hue augmentation
            hsv_s=0.7,               # HSV-Saturation augmentation
            hsv_v=0.4,               # HSV-Value augmentation
            degrees=10.0,             # rotation augmentation
            translate=0.1,            # translation augmentation
            scale=0.5,               # scale augmentation
            shear=0.0,               # shear augmentation
            perspective=0.0,          # perspective augmentation
            flipud=0.0,              # flip up-down (don't flip for tabletop)
            fliplr=0.5,              # flip left-right
            mosaic=1.0,              # mosaic augmentation
            mixup=0.0,               # mixup augmentation
            copy_paste=0.0,          # copy-paste augmentation
            # Validation
            val=True,
            save=True,
            save_period=10,          # save checkpoint every 10 epochs
            project=os.path.join(os.path.dirname(os.path.abspath(__file__)), 'runs', 'train'),
            name='taskb_ycb',
            exist_ok=True,
            pretrained=True,
            optimizer='AdamW',
            verbose=True,
            seed=42,
            resume=args.resume,
        )

        print(f"\n[1/2] Training complete!")
        print(f"  Best model: runs/train/taskb_ycb/weights/best.pt")

    except ImportError:
        print("ERROR: ultralytics not installed. Run: pip install ultralytics")
        sys.exit(1)
    except Exception as e:
        print(f"ERROR during training: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

    # ---- 导出 ONNX ----
    if args.export:
        print("\n[2/2] Exporting to ONNX...")
        try:
            from ultralytics import YOLO
            best_path = 'runs/train/taskb_ycb/weights/best.pt'
            if os.path.exists(best_path):
                model = YOLO(best_path)
                
                # Export ONNX
                onnx_path = model.export(
                    format='onnx',
                    imgsz=args.imgsz,
                    half=True,        # FP16
                    device=args.device,
                    optimize=True,
                )
                print(f"  ONNX model: {onnx_path}")

                # Export TensorRT (if available)
                try:
                    trt_path = model.export(
                        format='engine',
                        imgsz=args.imgsz,
                        half=True,
                        device=args.device,
                    )
                    print(f"  TensorRT engine: {trt_path}")
                except Exception as e:
                    print(f"  TensorRT export skipped: {e}")
                    print(f"  (Install tensorrt package if needed)")

            else:
                print(f"  ERROR: best.pt not found at {best_path}")

        except Exception as e:
            print(f"  Export failed: {e}")

    # ---- 部署提示 ----
    print("\n" + "=" * 60)
    print("  TRAINING PIPELINE COMPLETE")
    print("=" * 60)
    print(f"""
To use the fine-tuned model in perception_pipeline.py:
  1. Copy best.pt:
     cp runs/train/taskb_ycb/weights/best.pt ./taskb_ycb.pt

  2. Update perception_pipeline.py line ~56:
     Change: models = ['yolo11s']
     To:     models = ['taskb_ycb.pt']

  3. Test:
     python test_offline.py
""")

    # ---- 训练结果分析 ----
    print("\nTraining metrics:")
    results_dir = Path('runs/train/taskb_ycb')
    if results_dir.exists():
        for metric_file in ['results.csv', 'results.png']:
            if (results_dir / metric_file).exists():
                print(f"  {results_dir / metric_file}")
    print("\nTo view training curves:")
    print(f"  Open runs/train/taskb_ycb/results.png")


if __name__ == "__main__":
    main()